services:
  app:
    depends_on:
      - influxdb
    build:
      context: .
      dockerfile: ./Dockerfile
      tags:
        - "psmon-release:latest"
      args:
        HOST: 0.0.0.0
        PORT: 8000
    init: true
    restart: no
    ports:
      - ${HOST:-127.0.0.1}:${PORT:-8000}:8000
    environment:
      ROOTFS_PATH: ${ROOTFS_PATH:-/rootfs}
      TOP_PROCESS_COUNT: ${TOP_PROCESS_COUNT:-10}
      INFLUXDB_URL: http://${INFLUXDB_HOST:-influxdb}:${INFLUXDB_PORT:-8086}
      INFLUXDB_TOKEN: ${INFLUXDB_INIT_ADMIN_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_INIT_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_INIT_BUCKET}
    volumes:
      - /:${ROOTFS_PATH:-/rootfs}:ro

  influxdb:
    image: influxdb:2
    container_name: influxdb
    #    ports:
    #      - ${HOST:-127.0.0.1}:${INFLUXDB_PORT:-8086}:8086
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: ${INFLUXDB_INIT_MODE:-setup}
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_INIT_USERNAME:-admin}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_INIT_PASSWORD:-supersecurepassword}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_INIT_ORG:-my-org}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_INIT_BUCKET:-system-metrics}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_INIT_ADMIN_TOKEN:-my-secret-token}

volumes:
  influxdb-data:
